---
openafs_admin: admin.admin
openafs_cell: example.com
openafs_org: Example
openafs_realm: EXAMPLE.COM
openafs_server_package: openafs-server
openafs_yum_repo: https://download.sinenomine.net/openafs/repo/sna-openafs-release-latest.noarch.rpm

openafs_path:
  viceetcdir: /usr/vice/etc
  afscachedir: /usr/vice/cache

#server: "{{ groups['openafs_fileservers'][0] }}"
#part: "{{ hostvars[groups['openafs_fileservers'][0]]['vicep'][0] }}"
server: afs04.example.com
part: a

kinit: /usr/bin/kinit
aklog: /usr/bin/aklog
fs: /usr/bin/fs
vos: /usr/sbin/vos
